# Generated by Django 5.2.5 on 2025-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_order_cancel_reason_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
