# Generated by Django 5.2.5 on 2025-11-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_item_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[(None, 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=20, null=True),
        ),
    ]
