# Generated by Django 5.2.5 on 2025-12-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_orderitem_cancel_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_approved_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_approved_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_requested',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_requested_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_status',
        ),
    ]
