# Generated by Django 5.2.5 on 2026-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variant',
        ),
    ]
