# Generated by Django 5.2.5 on 2026-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price_at_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='offer_percentage_at_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price_at_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
