# Generated by Django 5.2.5 on 2026-01-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_cartitem_discounted_price_at_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount refunded to wallet', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('completed', 'Refund Completed'), ('failed', 'Refund Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
